#!/usr/bin/env python3
"""
summarize_rollups.py — Phase 2 of the OneNote summarisation pipeline.

Reads page summaries from 03_Summaries and synthesises groups of related
pages into rollup summaries, using the manifest level/order hierarchy to
know which pages belong together.

Three rollup levels (all generated by default):

  1. Sub-group  — level-0 parent page + its level-1 children
                  e.g. "Annual Security Reports" synthesising M-trends + DBIR
                  Output: 03_Summaries/…/Section/_rollup_ParentName.md

  2. Section    — all sub-group rollups (or page summaries) within a section
                  Output: 03_Summaries/…/Section/_section_rollup.md

  3. Notebook   — all section rollups for a notebook
                  Output: 03_Summaries/Notebook/_notebook_rollup.md

Regeneration criteria (per rollup file):
  • File does not exist
  • Child count changed  (page added or removed)
  • Children hash changed (different set of child pages)
  • Any child summary has a newer 'summarised' date than the rollup
  • --force flag

Prerequisites:
  • Run patch_manifest_hierarchy.py first to populate level/order in manifests.
  • Run summarize_pages.py first to generate the page summaries.
"""

import os
import sys
import json
import time
import hashlib
import argparse
import requests
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
from google import genai

# ---------------------------------------------------------------------------
# CONFIGURATION  (mirrors summarize_pages.py)
# ---------------------------------------------------------------------------

load_dotenv()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

OLLAMA_HOST    = "http://10.254.254.48:11434"
OLLAMA_MODEL   = "qwen2.5:32b"
OLLAMA_TIMEOUT = 600

GEMINI_MODELS = {
    "g": ("gemini-2.5-flash", "gemini-2.5-flash  (fast, cloud)"),
    "f": ("gemini-2.5-pro",   "gemini-2.5-pro    (more capacity, cloud)"),
}
GEMINI_CALL_DELAY = 2

OLLAMA_MODEL_LABELS = {
    "qwen2.5:14b":          "qwen2.5:14b         (14B, balanced)",
    "qwen2.5:32b":          "qwen2.5:32b         (32B, higher quality — default)",
    "llama4:latest":        "llama4              (108B, powerful, very slow on CPU)",
    "mistral-large:latest": "mistral-large       (123B, strong reasoning, slow)",
    "gemma3:12b":           "gemma3:12b          (12B, fast, lighter)",
    "phi4-mini:latest":     "phi4-mini           (3.8B, fastest, basic quality)",
}

_llm_backend    = "ollama"
_llm_model_name = OLLAMA_MODEL
_gemini_client  = None

VAULT_DIR = Path("onenote_audit")
RAW_DIR   = VAULT_DIR / "01_Raw_Audit"
SUM_DIR   = VAULT_DIR / "03_Summaries"

# Sections handled by summarize_pages.py — skip rollup generation
SKIP_SECTIONS = {"candidates"}

# Minimum number of child summaries needed to generate a sub-group rollup
MIN_CHILDREN = 2

# ---------------------------------------------------------------------------
# PROMPTS
# ---------------------------------------------------------------------------

SUBGROUP_PROMPT = """\
You are synthesising summaries of related documents grouped under the topic "{parent}".

Each document summary is separated by "---". Write a cohesive synthesis that:
1. Identifies the main themes and findings across all documents
2. Highlights key facts, statistics, or decisions
3. Notes comparisons, contrasts, or complementary insights between documents
4. Is written in clear prose — do not just list each document in sequence

At the end, on a new line starting with "TAGS:", suggest 3-8 short lowercase tags.

Document summaries:
{content}
"""

SECTION_PROMPT = """\
You are synthesising the key content of the "{section}" section from a knowledge base.

The following are summaries of sub-topics and documents within this section, \
separated by "---". Write an executive summary that captures:
1. The overall purpose or theme of this section
2. The most important insights, decisions, or findings
3. Any recurring patterns or relationships across sub-topics

At the end, on a new line starting with "TAGS:", suggest 3-8 short lowercase tags.

Sub-topic summaries:
{content}
"""

NOTEBOOK_PROMPT = """\
You are writing a high-level overview of the "{notebook}" knowledge base.

The following are section summaries, separated by "---". Write a concise overview that:
1. Describes what this notebook covers and its main purpose
2. Highlights the most important content across all sections
3. Identifies any cross-section themes or relationships

At the end, on a new line starting with "TAGS:", suggest 3-8 short lowercase tags.

Section summaries:
{content}
"""

# ---------------------------------------------------------------------------
# LOGGING
# ---------------------------------------------------------------------------

_log_file = None

def log(msg=""):
    print(msg)
    if _log_file:
        _log_file.write(msg + "\n")

# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------

def format_eta(seconds):
    if seconds < 60:   return f"{int(seconds)}s"
    if seconds < 3600: return f"{int(seconds // 60)}m {int(seconds % 60)}s"
    return f"{int(seconds // 3600)}h {int((seconds % 3600) // 60)}m"


def parse_frontmatter(text):
    meta, body = {}, text
    if text.startswith("---"):
        end = text.find("---", 3)
        if end != -1:
            for line in text[3:end].splitlines():
                if ":" in line:
                    k, _, v = line.partition(":")
                    meta[k.strip()] = v.strip().strip('"')
            body = text[end + 3:].strip()
    return meta, body


def parse_tags(response):
    body_lines, tags = [], []
    for line in response.strip().splitlines():
        if line.strip().upper().startswith("TAGS:"):
            raw  = line.strip().split(":", 1)[1]
            tags = [t.strip().lower().replace(" ", "-") for t in raw.split(",") if t.strip()]
        else:
            body_lines.append(line)
    return "\n".join(body_lines).strip(), tags


def fingerprint(names):
    """Short MD5 of a sorted list of names — detects additions and removals."""
    h = hashlib.md5()
    for n in sorted(names):
        h.update(n.encode())
    return h.hexdigest()[:8]


def needs_update(rollup_path, child_paths, child_names, force):
    """
    Return (should_regenerate: bool, reason: str).

    Checks in order:
      1. force flag or file missing
      2. child count or set changed
      3. any child summary newer than this rollup
    """
    if force:
        return True, "force"
    if not rollup_path.exists():
        return True, "new"

    try:
        meta, _ = parse_frontmatter(rollup_path.read_text(encoding="utf-8"))
    except Exception:
        return True, "unreadable"

    # --- fingerprint check ---
    cur_hash  = fingerprint(child_names)
    cur_count = len(child_names)
    if meta.get("children_hash", "") != cur_hash:
        return True, "children changed"
    if int(meta.get("child_count", 0)) != cur_count:
        return True, "child count changed"

    # --- timestamp check ---
    stored_date = meta.get("summarised", "")
    if stored_date:
        try:
            rollup_dt = datetime.fromisoformat(stored_date)
            for cp in child_paths:
                if cp.exists():
                    cm, _ = parse_frontmatter(cp.read_text(encoding="utf-8"))
                    cd = cm.get("summarised", "")
                    if cd and datetime.fromisoformat(cd) > rollup_dt:
                        return True, f"child updated ({cp.stem})"
        except Exception:
            return True, "date parse error"

    return False, "up to date"


def write_rollup(rollup_path, rollup_type, notebook, section, title,
                 summary, tags, child_names):
    """Write a rollup file with full frontmatter."""
    tag_str = "[" + ", ".join(tags) + "]"
    fm = [
        "---",
        f'notebook: "{notebook}"',
    ]
    if section:
        fm.append(f'section: "{section}"')
    fm += [
        f'title: "{title}"',
        f'rollup_type: "{rollup_type}"',
        f'child_count: {len(child_names)}',
        f'children_hash: "{fingerprint(child_names)}"',
        f'tags: {tag_str}',
        f'summarised: "{datetime.now().strftime("%Y-%m-%d")}"',
        f'summarised_by: "{_llm_model_name}"',
        "---\n",
    ]
    rollup_path.parent.mkdir(parents=True, exist_ok=True)
    rollup_path.write_text("\n".join(fm) + f"# {title}\n\n{summary}\n", encoding="utf-8")

# ---------------------------------------------------------------------------
# LLM  (mirrors summarize_pages.py)
# ---------------------------------------------------------------------------

def call_ollama(prompt):
    try:
        resp = requests.post(
            f"{OLLAMA_HOST}/api/generate",
            json={"model": _llm_model_name, "prompt": prompt, "stream": False},
            timeout=OLLAMA_TIMEOUT,
        )
        resp.raise_for_status()
        return resp.json()["response"].strip()
    except requests.exceptions.Timeout:
        log(f"    [Error]: Ollama timed out after {OLLAMA_TIMEOUT}s")
        return None
    except Exception as e:
        log(f"    [Error]: {e}")
        return None


def call_gemini(prompt):
    time.sleep(GEMINI_CALL_DELAY)
    wait = 20
    for attempt in range(3):
        try:
            return _gemini_client.models.generate_content(
                model=_llm_model_name, contents=prompt
            ).text.strip()
        except Exception as e:
            if "503" in str(e) and attempt < 2:
                log(f"    [Retry {attempt+1}/3 in {wait}s]: {e}")
                time.sleep(wait)
                wait = min(wait + 20, 60)
            else:
                log(f"    [Error]: {e}")
                return None
    return None


def call_llm(prompt):
    return call_gemini(prompt) if _llm_backend == "gemini" else call_ollama(prompt)


def run_rollup(prompt_template, format_args, rollup_path, rollup_type,
               notebook, section, title, child_paths, child_names):
    """
    Check freshness, call LLM, write rollup.
    Returns the rollup_path if successful/skipped, None on error.
    """
    do_it, reason = needs_update(rollup_path, child_paths, child_names, force)

    if not do_it:
        log(f"    [Skip — {reason}]: {rollup_path.name}")
        return rollup_path   # return path so parent level can include it

    log(f"    Generating [{reason}]: {rollup_path.name}")

    # Build content blocks from each input file
    blocks = []
    for cp in child_paths:
        if not cp.exists():
            continue
        _, body = parse_frontmatter(cp.read_text(encoding="utf-8"))
        if body.strip():
            blocks.append(f"## {cp.stem}\n\n{body}")

    if len(blocks) < MIN_CHILDREN:
        log(f"    [Skip — fewer than {MIN_CHILDREN} summaries available]")
        return None

    combined = "\n\n---\n\n".join(blocks)
    prompt   = prompt_template.format(**format_args, content=combined)

    t_start  = time.time()
    response = call_llm(prompt)
    elapsed  = time.time() - t_start

    if response is None:
        return None

    summary, llm_tags = parse_tags(response)

    # Auto-tags: notebook + section + type marker
    auto_tags = [notebook.lower().replace(" ", "-")]
    if section:
        auto_tags.append(section.split(" / ")[-1].lower().replace(" ", "-"))
    auto_tags.append(rollup_type.replace("_", "-"))
    all_tags = auto_tags + [t for t in llm_tags if t not in auto_tags]

    write_rollup(rollup_path, rollup_type, notebook, section, title,
                 summary, all_tags, child_names)

    log(f"      [{elapsed:.1f}s | {len(combined):,} chars input]")
    return rollup_path

# ---------------------------------------------------------------------------
# MANIFEST / HIERARCHY HELPERS
# ---------------------------------------------------------------------------

def load_manifest(nb_dir):
    path = nb_dir / "manifest.json"
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {"pages": {}}


def build_section_map(pages_meta):
    """
    Group manifest pages by section key (everything before the last '/').
    Each group is a list of page dicts sorted by 'order'.

    Returns: {section_key: [{"name", "key", "level", "order"}, ...]}
    """
    sections = {}
    for key, meta in pages_meta.items():
        parts = key.rsplit("/", 1)
        sec_key   = parts[0] if len(parts) == 2 else ""
        page_name = parts[-1]
        sections.setdefault(sec_key, []).append({
            "name":  page_name,
            "key":   key,
            "level": meta.get("level", 0),
            "order": meta.get("order", 0),
        })
    for pages in sections.values():
        pages.sort(key=lambda p: p["order"])
    return sections


def group_by_parent(pages):
    """
    Walk a list of pages sorted by order and group level-1 sub-pages under
    the level-0 parent that precedes them.

    Returns: [{"parent": page_dict_or_None, "children": [page_dict, ...]}]

    • level-0 pages → new group, may accumulate children
    • level-1 pages → appended to current group's children
    • Orphaned level-1 pages (no preceding level-0) → group with parent=None
    """
    groups  = []
    current = None
    for p in pages:
        if p["level"] == 0:
            current = {"parent": p, "children": []}
            groups.append(current)
        else:
            if current is None:
                current = {"parent": None, "children": []}
                groups.append(current)
            current["children"].append(p)
    return groups

# ---------------------------------------------------------------------------
# ARGUMENT PARSING + BANNER
# ---------------------------------------------------------------------------

parser = argparse.ArgumentParser(description="Generate rollup summaries")
parser.add_argument("--force",  action="store_true", help="Regenerate all rollups")
parser.add_argument(
    "--levels", default="all",
    choices=["subgroup", "section", "notebook", "all"],
    help="Which rollup levels to generate (default: all)"
)
args = parser.parse_args()

DO_SUBGROUP  = args.levels in ("subgroup",  "all")
DO_SECTION   = args.levels in ("section",   "all")
DO_NOTEBOOK  = args.levels in ("notebook",  "all")
force        = args.force

print("=" * 60)
print("  OneNote Page Summaries → Rollups")
print("=" * 60)
print(f"  Source : {SUM_DIR.resolve()}")
lvl_str = " + ".join(
    l for l, on in [("subgroup", DO_SUBGROUP), ("section", DO_SECTION), ("notebook", DO_NOTEBOOK)]
    if on
)
print(f"  Levels : {lvl_str}")
print()

# --- Log file ---
os.makedirs(str(VAULT_DIR), exist_ok=True)
log_path  = str(VAULT_DIR / f"03_Rollups-log_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.txt")
_log_file = open(log_path, "w", encoding="utf-8", buffering=1)
log(f"Logging to: {log_path}\n")

# ---------------------------------------------------------------------------
# MODEL SELECTION  (identical to summarize_pages.py)
# ---------------------------------------------------------------------------

_ollama_models = []
try:
    r = requests.get(f"{OLLAMA_HOST}/api/tags", timeout=10)
    r.raise_for_status()
    _ollama_models = sorted(m["name"] for m in r.json().get("models", []))
except Exception:
    pass

print("LLM model for rollup generation:")
for key, (_, label) in GEMINI_MODELS.items():
    print(f"  {key}  — Gemini: {label}")
if _ollama_models:
    for idx, name in enumerate(_ollama_models, 1):
        label = OLLAMA_MODEL_LABELS.get(name, name)
        print(f"  {idx}  — Ollama: {label}")
else:
    print(f"  (Ollama unreachable at {OLLAMA_HOST})")
print()

llm_choice = input(f"Model choice [{OLLAMA_MODEL}]: ").strip().lower()
print()

if llm_choice in GEMINI_MODELS:
    _llm_backend    = "gemini"
    _llm_model_name, model_label = GEMINI_MODELS[llm_choice]
    if not GEMINI_API_KEY:
        print("  ERROR: GEMINI_API_KEY not found in .env.")
        _log_file.close()
        sys.exit(1)
    _gemini_client = genai.Client(api_key=GEMINI_API_KEY)
    log(f"  LLM: Gemini — {model_label}\n")
elif llm_choice.isdigit() and 1 <= int(llm_choice) <= len(_ollama_models):
    _llm_backend    = "ollama"
    _llm_model_name = _ollama_models[int(llm_choice) - 1]
    log(f"  LLM: Ollama — {_llm_model_name}\n")
else:
    _llm_backend    = "ollama"
    _llm_model_name = OLLAMA_MODEL
    log(f"  LLM: Ollama — {_llm_model_name}\n")

if not force:
    answer = input("Overwrite existing rollups? (y/N): ").strip().lower()
    force  = answer == "y"
log(f"  Mode: {'overwrite' if force else 'resume'}\n")

# ---------------------------------------------------------------------------
# NOTEBOOK SELECTION
# ---------------------------------------------------------------------------

notebooks = sorted([d.name for d in SUM_DIR.iterdir() if d.is_dir()])
print("Available notebooks:")
for i, nb in enumerate(notebooks, 1):
    print(f"  {i:>2}. {nb}")
print()
print("  a           — all notebooks")
print("  s <numbers> — skip these    e.g. s 1 3")
print("  p <numbers> — only these    e.g. p 2 4")
print()

selection = input("Your choice: ").strip().lower()
if selection in ("a", ""):
    selected_nbs = notebooks
elif selection.startswith("s "):
    skip = {int(x) for x in selection[2:].split() if x.isdigit()}
    selected_nbs = [nb for i, nb in enumerate(notebooks, 1) if i not in skip]
elif selection.startswith("p "):
    pick = {int(x) for x in selection[2:].split() if x.isdigit()}
    selected_nbs = [notebooks[i-1] for i in pick if 1 <= i <= len(notebooks)]
else:
    log("Unrecognised input — processing all notebooks.")
    selected_nbs = notebooks

log(f"\nNotebooks selected:")
for nb in selected_nbs:
    log(f"  - {nb}")
log()

# ---------------------------------------------------------------------------
# MAIN LOOP
# ---------------------------------------------------------------------------

total_generated  = 0
total_skipped    = 0
total_errors     = 0
processing_times = []
script_start     = time.time()

for notebook in selected_nbs:
    nb_dir     = RAW_DIR / notebook
    manifest   = load_manifest(nb_dir)
    pages_meta = manifest.get("pages", {})

    if not pages_meta:
        log(f"[Skip — no manifest]: {notebook}\n")
        continue

    has_hierarchy = any(v.get("level", 0) > 0 for v in pages_meta.values())
    if not has_hierarchy:
        log(f"[Skip — no hierarchy data]: {notebook}")
        log(f"  → Run patch_manifest_hierarchy.py first, then retry.\n")
        continue

    log(f"Notebook: {notebook}")
    section_map          = build_section_map(pages_meta)
    section_rollup_paths = []   # accumulated for notebook rollup

    for sec_key, pages in sorted(section_map.items()):

        # Skip sections handled elsewhere (e.g. Candidates)
        leaf_section = sec_key.split("/")[-1].lower() if sec_key else ""
        if leaf_section in SKIP_SECTIONS:
            log(f"  [Skip section — {leaf_section}]: {sec_key}")
            continue

        section_display = sec_key.replace("/", " / ") if sec_key else notebook
        section_folder  = SUM_DIR / notebook / sec_key if sec_key else SUM_DIR / notebook

        groups = group_by_parent(pages)

        # ----------------------------------------------------------------
        # LEVEL 1 — SUB-GROUP ROLLUPS
        # Each level-0 parent with ≥ MIN_CHILDREN level-1 children
        # ----------------------------------------------------------------
        # section_inputs: what to feed into the section rollup.
        # Prefer sub-group rollups; fall back to raw page summaries.
        section_inputs = []

        if DO_SUBGROUP:
            for g in groups:
                parent   = g["parent"]
                children = g["children"]

                if not parent:
                    # Orphaned sub-pages — include their summaries in section
                    for c in children:
                        p = section_folder / f"{c['name']}.md"
                        if p.exists():
                            section_inputs.append(p)
                    continue

                parent_sum = section_folder / f"{parent['name']}.md"

                if len(children) < MIN_CHILDREN:
                    # Not enough children — use parent summary directly
                    if parent_sum.exists():
                        section_inputs.append(parent_sum)
                    continue

                child_names  = [c["name"] for c in children]
                child_paths  = [section_folder / f"{n}.md" for n in child_names]
                available    = [p for p in child_paths if p.exists()]

                if len(available) < MIN_CHILDREN:
                    log(f"  [Skip subgroup — only {len(available)} summaries found]: {parent['name']}")
                    if parent_sum.exists():
                        section_inputs.append(parent_sum)
                    continue

                rollup_path = section_folder / f"_rollup_{parent['name']}.md"

                # Include parent's own summary as the first block (if it has content)
                input_paths = ([parent_sum] if parent_sum.exists() else []) + available
                input_names = (
                    ([parent["name"] + " (overview)"] if parent_sum.exists() else [])
                    + child_names
                )

                t0 = time.time()
                result = run_rollup(
                    SUBGROUP_PROMPT,
                    {"parent": parent["name"]},
                    rollup_path, "subgroup",
                    notebook, section_display,
                    f"Rollup: {parent['name']}",
                    input_paths, input_names,
                )
                elapsed = time.time() - t0

                if result is not None:
                    section_inputs.append(result)
                    if rollup_path.exists():
                        # Only count as generated if it was freshly written
                        meta, _ = parse_frontmatter(rollup_path.read_text(encoding="utf-8"))
                        if meta.get("summarised", "") == datetime.now().strftime("%Y-%m-%d"):
                            total_generated += 1
                            processing_times.append(elapsed)
                        else:
                            total_skipped += 1
                else:
                    total_errors += 1
                    if parent_sum.exists():
                        section_inputs.append(parent_sum)   # degrade gracefully

        else:
            # Sub-group level not requested — collect all page summaries for section rollup
            for p in pages:
                sp = section_folder / f"{p['name']}.md"
                if sp.exists():
                    section_inputs.append(sp)

        # ----------------------------------------------------------------
        # LEVEL 2 — SECTION ROLLUP
        # ----------------------------------------------------------------
        if DO_SECTION:
            inputs = [p for p in section_inputs if p.exists()]

            if len(inputs) < MIN_CHILDREN:
                log(f"  [Skip section rollup — only {len(inputs)} inputs]: {sec_key or notebook}")
            else:
                child_names = [p.stem for p in inputs]
                rollup_path = section_folder / "_section_rollup.md"

                t0 = time.time()
                result = run_rollup(
                    SECTION_PROMPT,
                    {"section": section_display},
                    rollup_path, "section",
                    notebook, section_display,
                    f"Section Summary: {section_display}",
                    inputs, child_names,
                )
                elapsed = time.time() - t0

                if result is not None:
                    section_rollup_paths.append(result)
                    if rollup_path.exists():
                        meta, _ = parse_frontmatter(rollup_path.read_text(encoding="utf-8"))
                        if meta.get("summarised", "") == datetime.now().strftime("%Y-%m-%d"):
                            total_generated += 1
                            processing_times.append(elapsed)
                        else:
                            total_skipped += 1
                else:
                    total_errors += 1

    # --------------------------------------------------------------------
    # LEVEL 3 — NOTEBOOK ROLLUP
    # --------------------------------------------------------------------
    if DO_NOTEBOOK:
        inputs = [p for p in section_rollup_paths if p.exists()]

        if len(inputs) < MIN_CHILDREN:
            log(f"  [Skip notebook rollup — only {len(inputs)} section rollups]: {notebook}")
        else:
            child_names = [p.parent.name for p in inputs]   # section folder names
            rollup_path = SUM_DIR / notebook / "_notebook_rollup.md"

            t0 = time.time()
            result = run_rollup(
                NOTEBOOK_PROMPT,
                {"notebook": notebook},
                rollup_path, "notebook",
                notebook, "",
                f"Notebook Summary: {notebook}",
                inputs, child_names,
            )
            elapsed = time.time() - t0

            if result is not None:
                if rollup_path.exists():
                    meta, _ = parse_frontmatter(rollup_path.read_text(encoding="utf-8"))
                    if meta.get("summarised", "") == datetime.now().strftime("%Y-%m-%d"):
                        total_generated += 1
                        processing_times.append(elapsed)
                    else:
                        total_skipped += 1
            else:
                total_errors += 1

    log()

# ---------------------------------------------------------------------------
# FINAL SUMMARY
# ---------------------------------------------------------------------------

total_elapsed = time.time() - script_start
log(f"{'=' * 60}")
log(f"  ROLLUP COMPLETE")
log(f"{'=' * 60}")
log(f"  Generated : {total_generated}")
log(f"  Skipped   : {total_skipped}  (up to date)")
log(f"  Errors    : {total_errors}")
log(f"  Total time: {format_eta(total_elapsed)}")
if processing_times:
    avg = sum(processing_times) / len(processing_times)
    log(f"  Avg/rollup: {format_eta(avg)}")
    log(f"  Fastest   : {format_eta(min(processing_times))}")
    log(f"  Slowest   : {format_eta(max(processing_times))}")
log(f"  Output    : {SUM_DIR.resolve()}")
_log_file.close()
